## プロジェクトのセルフプロビジョニングを無効にする

[Warning]
====
続行する前に、LDAPラボが終わっていることを確認してください。
====

OpenShiftはデフォルトで、認証されたユーザーがアプリケーションを論理的に収容するための *Projects* を
作成することができます。この機能により、管理者は「PaaS」（Platform as a Service）モデルの登場によって
広まった「セルフサービス」機能を提供することができます。

この機能は、すべての状況に適用できるとは限りません。多くの管理者は、プロジェクトとプロジェクトが作成できる人（誰でも）
を制御できるようにしたいと考えるかもしれません。このような使用例としては、以下のようなものがあります。

* 環境の保護 - 管理者は、自分の知らないところでプロジェクトが作成されることを望まないかもしれません。
* リソース割り当て - 管理者は、リソース割り当てを細かく制御したい場合があります（例：「オーバーコミットしたくない」）。
* クオータの柔軟性 - デフォルトのクオータを設定することができますが、管理者はプロジェクトの範囲に応じて追加のクオータを指定（または少なく）することができます。
* 会計とチャージバック - マルチテナントシステムでは、会計とチャージバックを行う必要がある場合があります。
* 一般的な管理コントロール - 管理者は、環境内で何が行われるかを完全にコントロールしたい場合があります。

[Note]
====
このような制御を行うには、プロジェクトのセルフプロビジョニングを無効にする以外にも方法があります。
====

### 背景: プロジェクト
何を無効にしているのでしょうか？以前のラボで、プロジェクトはアプリケーションのすべてのリソースを
保持する「バケット」のようなものであることを学びました。また、プロジェクトはコラボレーションするために
ユーザーやグループに割り当てることができることも学びました。しかし、プロジェクトとKubernetes Namespaceの違いは何なのでしょうか？

プロジェクトはKubernetes Namespaceに直接マッピングされます。また、内部レジストリのネームスペースや
VXLANのVNIDにもマッピングされます。つまり、プロジェクトへのアクセスを許可することは、ユーザーにコラボレーションを
させる以上の効果があるのです。ネットワーク通信、レジストリネームスペースへのアクセス、
Kubernetes Namespace内のオブジェクトへのアクセスを許可することになるのです。

#### Clusterrolebindingを検証する
`self-provisioners` の `clusterrolebinding` を調べるには、*kubeadmin* になる必要があります。

[Note]
====
以前のラボで使用した serviceaccount ユーザーを使用することもできます。
`kubeadmin` とサービスアカウントユーザーはどちらも `cluster-admin` のロールを持つので、実際には問題ありません。
====

[source,bash,role="execute"]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }}
----

self-provisioners` クラスタロールのバインディングの使用状況を `oc describe` コマンドで確認することができます。

[source,bash,role="execute"]
----
oc describe clusterrolebinding.rbac self-provisioners
----

次のような出力が表示されるはずです。

----
Name:         self-provisioners
Labels:       <none>
Annotations:  rbac.authorization.kubernetes.io/autoupdate: true
Role:
  Kind:  ClusterRole
  Name:  self-provisioner
Subjects:
  Kind   Name                        Namespace
  ----   ----                        ---------
  Group  system:authenticated:oauth
----

ここでは、グループ `system:authenticated:oauth` (デフォルトでは、認証したすべてのユーザーが属するグループ) が
`self-provisioners` ロールにバインドされていることを述べています。
このロールは、ユーザーがプロジェクトを作成することを可能にするOpenShiftの組み込みのロールです。

[Note]
====
OpenShiftに付属する様々なロールに興味がある方は、
リンク:https://docs.openshift.com/container-platform/4.9/authentication/using-rbac.html[ロールベースアクセスコントロール（RBAC）^]
のドキュメントで詳細をご覧いただけます。
====

設定そのものを見るには、以下を実行してyamlを検査します。
[source,bash,role="execute"]
----
oc get clusterrolebinding.rbac self-provisioners -o yaml
----

構成は次のようになります。

[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2022-02-14T22:25:08Z"
  name: self-provisioners
  resourceVersion: "10620"
  uid: a0098c02-b9cb-4815-aebd-7dc44ef4d163
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: self-provisioner
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated:oauth
----

#### セルフプロビジョンプロジェクトを削除する
self-provisioner`クラスタロールを `system:authenticated:oauth` グループから
削除するには、そのグループをロールバインドから削除する必要があります。

[source,bash,role="execute"]
----
oc patch clusterrolebinding.rbac self-provisioners -p '{"subjects": null}'
----

自動アップデートにより、クラスタロールはデフォルトの状態にリセットされます。
これを無効にするには、`rbac.authorization.kubernetes.io/autoupdate` という
アノテーションを実行して `false` に設定する必要があります。

[source,bash,role="execute"]
----
oc patch clusterrolebinding.rbac self-provisioners -p '{ "metadata": { "annotations": { "rbac.authorization.kubernetes.io/autoupdate": "false" } } }'
----

新しいコンフィギュレーションを表示します。

[source,bash,role="execute"]
----
oc get clusterrolebinding.rbac self-provisioners -o yaml
----

これでYAMLに `subjects` がないはずです。このような感じになるはずです。

[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "false"
  creationTimestamp: "2022-02-14T22:25:08Z"
  name: self-provisioners
  resourceVersion: "55489"
  uid: a0098c02-b9cb-4815-aebd-7dc44ef4d163
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: self-provisioner
----

`fancyuser1` としてログインし、プロジェクトを作成してテストしてください。

[source,bash,role="execute"]
----
oc login -u fancyuser1 -p Op#nSh1ft
oc new-project fancyuserproject
----

エラーメッセージが表示されるはずです。

----
Error from server (Forbidden): You may not request a new project via this API.
----

次の演習のために `kubeadmin` ユーザーとしてログインします。

[source,bash,role="execute"]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }}
----

#### リクエストメッセージのカスタマイズ
これで、ユーザーがプロジェクトを作成しようとすると、いつでも同じメッセージ
`You may not request a new project via this API(このAPIを使用して新しいプロジェクトをリクエストすることはできません)` が表示されるようになりました。
このメッセージをカスタマイズして、より意味のある行動喚起を行うことができます。

例えば、ユーザーがプロジェクトをリクエストするチケットを送信するようにすることができます。
これは、与えられたテキストを変更して、指示を含めることで実現できます。
[source,bash,role="execute"]
----
oc patch --type=merge project.config.openshift.io cluster -p '{"spec":{"projectRequestMessage":"Please visit https://ticket.example.com to request a project"}}'
----

Here, you are adding the `projectRequestMessage` and the value
`Please visit https://ticket.example.com to request a project` to the specification.

Before you can see this new message, you'll need to wait for the `apiserver` application
to rollout the changes. This can take some time to rollout, especially on a busy cluster.
[source,bash,role="execute"]
----
sleep 30
oc rollout status -n  openshift-apiserver deploy/apiserver
----

これで、ユーザがプロジェクトを作成しようとすると、このメッセージが表示されるようになりました。
`fancyuser1`のユーザーになってテストしてみてください。

[source,bash,role="execute"]
----
oc login -u fancyuser1 -p Op#nSh1ft
----

そして、プロジェクトを作成してみましょう。

[source,bash,role="execute"]
----
oc new-project fancyuserproject
----

以下のメッセージが表示されるはずです。

----
Error from server (Forbidden): Please visit https://ticket.example.com to request a project
----

#### クリーンアップ

次のラボに向けて、`kubeadmin`としてログインしていることを確認してください。

[source,bash,role="execute"]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }}
----

他のラボでは、`self-provisioners`ロールが必要な場合があるので、やったことを元に戻しておきましょう。

[source,bash,role="execute"]
----
oc patch clusterrolebinding.rbac self-provisioners -p '{"subjects":[{"apiGroup":"rbac.authorization.k8s.io","kind":"Group","name":"system:authenticated:oauth"}]}'
oc patch clusterrolebinding.rbac self-provisioners -p '{"metadata":{"annotations":{"rbac.authorization.kubernetes.io/autoupdate":"true"}}}'
oc patch --type=json project.config.openshift.io cluster -p '[{"op": "remove", "path": "/spec/projectRequestMessage"}]'
----
